# Generated by Django 3.0 on 2020-10-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('mobile_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_package_name', models.CharField(choices=[('Q', 'Quarter'), ('H', 'Half'), ('Y', 'Year')], default='Q', max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('customerob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
            ],
        ),
    ]
