# Generated by Django 3.0 on 2020-10-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=120)),
                ('arealocated', models.CharField(max_length=120)),
                ('famous_landmark', models.CharField(max_length=120)),
                ('pg_type', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PGDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main1', models.CharField(max_length=600)),
                ('main2', models.CharField(max_length=600)),
                ('single_sharing', models.CharField(max_length=600)),
                ('double_sharing', models.CharField(max_length=600)),
                ('three_sharing', models.CharField(max_length=600)),
                ('four_sharing', models.CharField(max_length=600)),
                ('kitchen', models.CharField(max_length=600)),
                ('bathroom', models.CharField(max_length=600)),
                ('location', models.CharField(max_length=600)),
                ('pg_ob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.PG')),
            ],
        ),
    ]
