# Generated by Django 3.0 on 2020-10-22 17:53

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=120)),
                ('arealocated', models.CharField(max_length=120)),
                ('famous_landmark', models.CharField(max_length=120)),
                ('pg_type', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='PGDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main1', models.FileField(upload_to=dashboard.models.pg_name_get)),
                ('main2', models.FileField(upload_to=dashboard.models.pg_name_get)),
                ('single_sharing', models.FileField(upload_to=dashboard.models.pg_name_get)),
                ('double_sharing', models.FileField(upload_to=dashboard.models.pg_name_get)),
                ('three_sharing', models.FileField(upload_to=dashboard.models.pg_name_get)),
                ('four_sharing', models.FileField(upload_to=dashboard.models.pg_name_get)),
                ('kitchen', models.FileField(upload_to=dashboard.models.pg_name_get)),
                ('bathroom', models.FileField(upload_to=dashboard.models.pg_name_get)),
                ('location', models.FileField(upload_to=dashboard.models.pg_name_get)),
                ('pg_ob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.PG')),
            ],
        ),
        migrations.AddField(
            model_name='pg',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customer'),
        ),
    ]
